import Newproduct6 from "../assets/images/branjlet.jpg";

const Products = [
  {
    id: 1,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 2,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 3,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 4,
    action: "-30%",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#FB1919",
    categoryTitle: "Bransjilet",
  },
  {
    id: 5,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 6,
    action: "-40%",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#FB1919",
    categoryTitle: "Bransjilet",
  },
  {
    id: 7,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 8,
    action: "-30%",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 9,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 10,
    action: "-30%",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 11,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 12,
    action: "-30%",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 13,
    action: "NEW",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
  {
    id: 14,
    action: "-30%",
    image: [
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
      Newproduct6,
    ],
    title: "Nike air Jordan Hoodie",
    price: 356000,
    delprice: 546000,
    color: "#265AD9",
    categoryTitle: "Bransjilet",
  },
];

export default Products;
