import Newproduct6 from "../assets/images/newproduct6.png";

const Products = [
  {
    id: 1,
    action: "NEW",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#265AD9",
  },
  {
    id: 2,
    action: "NEW",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#265AD9",
  },
  {
    id: 3,
    action: "NEW",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#265AD9",
  },
  {
    id: 4,
    action: "-30%",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#FB1919",
  },
  {
    id: 5,
    action: "NEW",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#265AD9",
  },
  {
    id: 6,
    action: "-40%",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#FB1919",
  },
  {
    id: 7,
    action: "NEW",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#265AD9",
  },
  {
    id: 8,
    action: "-30%",
    image: Newproduct6,
    title: "Nike air Jordan Hoodie",
    price: "356 000 uzs",
    delprice: "546 000 uzs",
    color: "#265AD9",
  },
];

export default Products;